spring:
  application:
    name: bbs

  web:
    resources:
      static-locations: file:/home/Serverman/SpringBoot/uploads/
      add-mappings: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bbs_db
    username: helloagain
    password: helloagain

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
